---
# handlers file for build
- name: Handler service state
  when: service_handler_state is defined
  ansible.builtin.systemd_service:
    name: "{{ service_name }}"
    state: "{{ service_handler_state }}"
