---
- name: Fail if molecule group is missing
  hosts: localhost
  tasks:
    - name: Print some info
      ansible.builtin.debug:
        msg: "{{ groups }}"

    - name: Assert group existence
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}

- name: Converge
  hosts: molecule
  # We disable gather facts because it would fail due to our container not
  # having python installed. This will not prevent use from running 'raw'
  # commands. Most molecule users are expected to use containers that already
  # have python installed in order to avoid notable delays installing it.
  gather_facts: false
  vars:
    apache_port: 8080
  tasks:
    - name: Check uname
      ansible.builtin.raw: uname -a
      register: result
      changed_when: false

    - name: Print some info
      ansible.builtin.assert:
        that: result.stdout | regex_search("^Linux")

    - name: Filter and return only selected facts
      ansible.builtin.setup:
        filter:
          - ansible_distribution

    - name: Testing role
      ansible.builtin.include_role:
        name: ../../roles/service
      vars:
        service_package: "{% if ansible_distribution == 'Ubuntu' %}apache2{% else %}httpd{% endif %}"
        service_name: "{% if ansible_distribution == 'Ubuntu' %}apache2{% else %}httpd{% endif %}"
        service_state: started
        service_enabled: true
        service_template_conf:
          - src: "./template/{% if ansible_distribution == 'Ubuntu' %}ports.ubuntu2204.conf{% else %}httpd.amazon2023.conf{% endif %}.j2"
            dest: "/etc/{% if ansible_distribution == 'Ubuntu' %}apache2/ports.conf{% else %}httpd/conf/httpd.conf{% endif %}"
            backup: true
        service_handler_state: reloaded
