---
# tasks file for host
- name: Import role "support_os"
  ansible.builtin.import_role:
    name: my_ansible_collections.linux.support_os

- name: Install package for DPKG
  when: ansible_distribution in ['Ubuntu']
  ansible.builtin.apt:
    name:
      - systemd
    state: present

- name: Install package for RPM (dnf)
  when: ansible_distribution in ['Amazon', 'AlmaLinux', 'RedHat']
  ansible.builtin.dnf:
    name:
      - systemd
    state: present

- name: Install package for RPM (yum)
  when: ansible_distribution in ['CentOS']
  ansible.builtin.yum:
    name:
      - systemd
    state: present

- name: Install package for DPKG
  when: ansible_distribution in ['Ubuntu'] and host_timezone is defined
  ansible.builtin.apt:
    name:
      - tzdata
    state: present

- name: Set timezone
  when: host_timezone is defined
  community.general.timezone:
    name: "{{ host_timezone }}"

- name: Install package for DPKG
  when: ansible_distribution in ['Ubuntu'] and host_name is defined
  ansible.builtin.apt:
    name:
      - hostname
    state: present

- name: Install package for RPM (dnf)
  when: ansible_distribution in ['Amazon', 'AlmaLinux', 'RedHat'] and host_name is defined
  ansible.builtin.dnf:
    name:
      - hostname
    state: present

- name: Install package for RPM (yum)
  when: ansible_distribution in ['CentOS'] and host_name is defined
  ansible.builtin.yum:
    name:
      - hostname
    state: present

- name: Set hostname
  when: host_name is defined
  ansible.builtin.hostname:
    name: "{{ host_name }}"
    use: "{% if ansible_distribution == 'Ubuntu' %}debian{% else %}systemd{% endif %}"
