---
# tasks file for hostname
- name: Import role "support_os"
  ansible.builtin.import_role:
    name: my_ansible_collections.linux.support_os

- name: Install package for DPKG
  when: ansible_distribution in ['Ubuntu']
  ansible.builtin.apt:
    name:
      - hostname
      - systemd
    state: present

- name: Install package for RPM (dnf)
  when: ansible_distribution in ['Amazon', 'AlmaLinux', 'RedHat']
  ansible.builtin.dnf:
    name:
      - hostname
      - systemd
    state: present

- name: Install package for RPM (yum)
  when: ansible_distribution in ['CentOS']
  ansible.builtin.yum:
    name:
      - hostname
      - systemd
    state: present

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname_name }}"
    use: "{% if ansible_distribution == 'Ubuntu' %}debian{% else %}systemd{% endif %}"
