---
# tasks file for user
- name: Import role "support_os"
  ansible.builtin.import_role:
    name: my_ansible_collections.linux.support_os

- name: Install package for DPKG
  when: ansible_distribution in ['Ubuntu']
  ansible.builtin.apt:
    name:
      - ssh
    state: present

- name: Install package for RPM (dnf)
  when: ansible_distribution in ['Amazon', 'AlmaLinux', 'RedHat']
  ansible.builtin.dnf:
    name:
      - openssh
      - util-linux
    state: present

- name: Install package for RPM (yum)
  when: ansible_distribution in ['CentOS']
  ansible.builtin.yum:
    name:
      - openssh
    state: present

- name: Add user
  ansible.builtin.user:
    name: "{{ user_name }}"
    comment: "{{ user_comment | default(omit) }}"
    generate_ssh_key: "{{ user_generate_ssh_key }}"
    group: "{{ user_group | default(omit) }}"
    groups: "{{ user_groups | default(omit) }}"
    home: "{{ user_home | default(omit) }}"
    shell: "{{ user_shell | default(omit) }}"
    ssh_key_bits: "{{ user_ssh_key_bits | default(omit) }}"
    ssh_key_comment: "{{ user_ssh_key_comment | default(omit) }}"
    ssh_key_file: "{{ user_ssh_key_file | default(omit) }}"
    ssh_key_passphrase: "{{ user_ssh_key_passphrase | default(omit) }}"
    ssh_key_type: "{{ user_ssh_key_type | default(omit) }}"
  register: _user_user_result

- name: Add symbolic link to ”~/.local/bin"
  when: user_home_local_bin is defined
  ansible.builtin.file:
    src: "{{ item.src | default(omit) }}"
    path: "{{ _user_user_result.home }}/.local/bin{% if item.symlink is defined %}/{{ item.symlink }}{% endif %}"
    owner: "{{ _user_user_result.name }}"
    group: "{{ _user_user_result.group }}"
    state: "{{ item.state | default('link') }}"
  loop: "{{ [{'state': 'directory'}] | union(user_home_local_bin) }}"
