---
dependency:
  name: galaxy
  options:
    requirements-file: ../default/requirements.yml
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
platforms:
  - name: molecule.role-build.ubuntu2204
    image: molecule/role-build/ubuntu2204
    pre_build_image: false
    dockerfile: ../role-build/docker/ubuntu2204.dockerfile
  - name: molecule.role-build.amazon2023
    image: public.ecr.aws/amazonlinux/amazonlinux:2023
  - name: molecule.role-build.alma9
    image: almalinux:9
  - name: molecule.role-build.rhel9
    image: redhat/ubi9-init
  - name: molecule.role-build.rhel8
    image: redhat/ubi8-init
  - name: molecule.role-build.cent7
    image: molecule/role-build/cent7
    pre_build_image: false
    dockerfile: ../role-build/docker/cent7.dockerfile
