---
- name: Verify
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Filter and return only selected facts
      ansible.builtin.setup:
        filter:
          - ansible_architecture

    - name: List directory and file
      ansible.builtin.stat:
        path: "{{ item }}"
      register: stat_list
      loop:
        - /usr/local/src/openssl-3.1.3
        - /usr/local/bin/openssl
        - /usr/local/lib{% if ansible_architecture == 'x86_64' %}64{% endif %}/libssl.so
        - /usr/local/lib{% if ansible_architecture == 'x86_64' %}64{% endif %}/libssl.so.3
        - /usr/local/lib{% if ansible_architecture == 'x86_64' %}64{% endif %}/libcrypto.so
        - /usr/local/lib{% if ansible_architecture == 'x86_64' %}64{% endif %}/libcrypto.so.3

    - name: Check directory or file exists
      ansible.builtin.assert:
        that: item.stat.exists
        fail_msg: "{{ item | to_json }}"
      loop: "{{ stat_list.results }}"
      loop_control:
        label: "{{ item.item }}"
