---
argument_specs:
  main:
    options:
      service_list:
        type: "list"
        elements: "dict"
        required: true
        options:
          package:
            type: "str"
            required: true
          name:
            type: "str"
            required: false
          state:
            type: "str"
            required: false
          enabled:
            type: "bool"
            required: false
          copy_conf:
            type: "list"
            elements: "dict"
            required: false
            options:
              src:
                type: "str"
                required: true
              dest:
                type: "str"
                required: true
              backup:
                type: "bool"
                required: false
              owner:
                type: "str"
                required: false
              group:
                type: "str"
                required: false
              mode:
                type: "str"
                required: false
          template_conf:
            type: "list"
            elements: "dict"
            required: false
            options:
              src:
                type: "str"
                required: true
              dest:
                type: "str"
                required: true
              backup:
                type: "bool"
                required: false
              owner:
                type: "str"
                required: false
              group:
                type: "str"
                required: false
              mode:
                type: "str"
                required: false
          lineinfile_conf:
            type: "list"
            elements: "dict"
            required: false
            options:
              path:
                type: "str"
                required: true
              regexp:
                type: "str"
                required: true
              line:
                type: "str"
                required: true
              insertafter:
                type: "str"
                required: false
              insertbefore:
                type: "str"
                required: false
              backup:
                type: "bool"
                required: false
              owner:
                type: "str"
                required: false
              group:
                type: "str"
                required: false
              mode:
                type: "str"
                required: false
          handler:
            type: "dict"
            required: false
            options:
              state:
                type: "str"
                required: true