---
- name: Verify
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Check timezone
      ansible.builtin.command: timedatectl
      register: result
      changed_when: false

    - name: Timezone assertion
      ansible.builtin.assert:
        that: "'Time zone: Asia/Tokyo (JST, +0900)' in result.stdout"
        fail_msg: "{{ result.stdout }}"
