---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Existed directory and file
      ansible.builtin.stat:
        path: "{{ item }}"
      register: exist_list
      loop:
        - /usr/local/src/openssl-3.1.3

    - name: Check directory or file exists
      ansible.builtin.assert:
        that: item.stat.exists
        fail_msg: "{{ item | to_json }}"
      loop: "{{ exist_list.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Not existed directory and file
      ansible.builtin.stat:
        path: "{{ item }}"
      register: notexist_list
      loop:
        - /usr/local/openssl-3.1
        - /usr/local/openssl-3.1/bin/openssl
        - /usr/local/openssl-3.1/lib/libssl.so
        - /usr/local/openssl-3.1/lib/libssl.so.3
        - /usr/local/openssl-3.1/lib/libcrypto.so
        - /usr/local/openssl-3.1/lib/libcrypto.so.3

    - name: Check directory or file not exists
      ansible.builtin.assert:
        that: not item.stat.exists
        fail_msg: "{{ item | to_json }}"
      loop: "{{ notexist_list.results }}"
      loop_control:
        label: "{{ item.item }}"
