---
- name: Verify
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Filter and return only selected facts
      ansible.builtin.setup:
        filter:
          - ansible_architecture

    - name: Execute "cat /etc/passwd"
      ansible.builtin.command: cat /etc/passwd
      register: cat_return

    - name: Check user
      ansible.builtin.assert:
        that: cat_return.stdout_lines | select('match', '^hoge:.*') | list | length == 1
        fail_msg: "{{ cat_return.stdout_lines | to_json }}"

    - name: Execute "openssl version"
      ansible.builtin.command: openssl version
      become: true
      become_user: hoge
      become_method: su
      become_flags: '-'
      register: openssl_return
      changed_when: false

    - name: Check OpenSSL version
      ansible.builtin.assert:
        that: "openssl_return.stdout == 'OpenSSL 3.1.3 19 Sep 2023 (Library: OpenSSL 3.1.3 19 Sep 2023)'"
        fail_msg: "{{ openssl_return | to_json }}"
