galaxy_info:
  author: Tatsuto Iijima
  description: A role that builds source with the command "make"
  license: Apache-2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Amazon Linux
      versions:
        - '2023'
    - name: EL
      versions:
        - '8'
        - '9'
  galaxy_tags:
    - make
    - install
