---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: molecule
  gather_facts: false
  tasks:
    - name: List directory and file
      ansible.builtin.stat:
        path: "{{ item }}"
      register: stat_list
      loop:
        - /usr/local/src/openssl-3.1.3
        - /usr/local/openssl-3.1
        - /usr/local/openssl-3.1/bin/openssl
        - /usr/local/openssl-3.1/lib/libssl.so
        - /usr/local/openssl-3.1/lib/libssl.so.3
        - /usr/local/openssl-3.1/lib/libcrypto.so
        - /usr/local/openssl-3.1/lib/libcrypto.so.3

    - name: Check directory or file exists
      ansible.builtin.assert:
        that: item.stat.exists
        fail_msg: "{{ item | to_json }}"
      loop: "{{ stat_list.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Execute command
      ansible.builtin.command: /usr/local/openssl-3.1/bin/openssl version
      register: result
      changed_when: false

    - name: Check OpenSSL version
      ansible.builtin.assert:
        that: "result.stdout == 'OpenSSL 3.1.3 19 Sep 2023 (Library: OpenSSL 3.1.3 19 Sep 2023)'"
        fail_msg: "{{ result | to_json }}"
